# .github/workflows/build.yaml
name: C
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/c.yaml'
      - 'src/**'
      
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/c.yaml'
      - 'src/**'

concurrency:
  group: ${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install GSL
        if: runner.os == 'macOS'
        run: brew install gsl
        
      - name: Install GSL
        if: runner.os == 'Windows'
        run: |
          pushd $RUNNER_TEMP
          curl --silent --show-error -L https://github.com/rwinlib/gsl/archive/v2.7.zip -o gsl.zip
          7z x gsl.zip
          popd
          cat<<EOF > Makevars.win
          # Set by Github Actions
          GSL_CFLAGS = -I${RUNNER_TEMP}/gsl-2.7/include
          GSL_LIBS   = -L"$(RUNNER_TEMP)/gsl-2.7/lib/x64" -lgsl -lgslcblas
          EOF
          cat Makevars.win
        shell: bash

      - run: make -C src all DEBUG=1 WARN_FLAGS='-Werror'
      - run: make -C src all DEBUG=0 WARN_FLAGS='-Werror'
      - name: Functional tests
        run: |
          ./bin/dominatedsets --help
          ./bin/dominatedsets --help
          ./bin/eaf --help
          ./bin/epsilon --help
          ./bin/hv --help
          ./bin/igd --help
          ./bin/ndsort --help
          ./bin/nondominated --help

