# .github/workflows/build.yaml
name: C
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/c.yaml'
      - 'src/**'
      
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/c.yaml'
      - 'src/**'

concurrency:
  group: ${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install GSL
        if: runner.os == 'macOS'
        run: brew install gsl
        
      - name: Install GSL
        if: runner.os == 'Windows'
        env:
          GSL_ROOT: ${{ runner.temp }}/gsl
        run: |
          mkdir $GSL_ROOT
          pushd $GSL_ROOT
          curl https://github.com/rwinlib/gsl/archive/v2.7.zip --output gsl.zip
          7z x gsl.zip
          popd
          cat<<EOF > Makevars
          # Set by Github Actions
          GSL_CFLAGS = -I$GSL_ROOT/include
          GSL_LIBS   = -L"$(GSL_ROOT)/lib64" -lgsl -lgslcblas
          EOF
          cat Makevars
        shell: bash

      - run: make -C src all DEBUG=1 WARN_FLAGS='-Werror'
      - run: make -C src all DEBUG=0 WARN_FLAGS='-Werror'
      - name: Functional tests
        run: |
          ./bin/dominatedsets --help
          ./bin/dominatedsets --help
          ./bin/eaf --help
          ./bin/epsilon --help
          ./bin/hv --help
          ./bin/igd --help
          ./bin/ndsort --help
          ./bin/nondominated --help

