name: C

on:
  push:
    branches-ignore: [gh-pages]
    paths:
      - '.github/workflows/C.yml'
      - 'src/**'
      
  pull_request:
    branches-ignore: [gh-pages]
    paths:
      - '.github/workflows/C.yml'
      - 'src/**'

jobs:
  build:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    name: Build C code on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, cc: gcc }
          - {os: ubuntu-latest, cc: gcc }
          - {os: macOS-latest, cc: clang }
          - {os: macOS-latest, cc: gcc }
    env:
      CC: ${{ matrix.config.cc }}
      
    steps:
      - uses: actions/checkout@v4
      - name: Install GSL
        if: runner.os == 'macOS'
        run: brew install gsl
        
      - name: Put MSYS2_MinGW64 on PATH
        if: runner.os == 'Windows'
        run: |
          echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{ runner.temp }}/msys64/mingw64/usr/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Install GSL
        if: runner.os == 'Windows'
        run: |
          pushd ${{ runner.temp }}
          curl --silent --show-error -L https://github.com/rwinlib/gsl/archive/v2.7.zip -o gsl.zip
          7z x gsl.zip
          popd
          echo "GSL_CFLAGS=-I${{ runner.temp }} }}{GITHUB_ACTION_PATH}/gsl-2.7/include" >> $GITHUB_ENV
          echo "GSL_LIBS=-L${{ runner.temp }}/gsl-2.7/lib/x64" >> $GITHUB_ENV
          echo "CC=$CC"
                  
      - run: cd src && ./configure
      - run: make -C src all DEBUG=1 WARN_FLAGS='-Werror'
      - run: make -C src all DEBUG=0 WARN_FLAGS='-Werror'
        
      - name: Functional tests
        run: |
          ./bin/dominatedsets --help
          ./bin/dominatedsets --help
          ./bin/eaf --help
          ./bin/epsilon --help
          ./bin/hv --help
          ./bin/igd --help
          ./bin/ndsort --help
          ./bin/nondominated --help

  msys2:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sys:
          - clang64
          - mingw64
          - ucrt64
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Disable autocrlf
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: |
            gcc
            gsl
            make
            pkg-config
          
      - run: cd src && ./configure
      - run: make -C src all DEBUG=1 WARN_FLAGS='-Werror'
      - run: make -C src all DEBUG=0 WARN_FLAGS='-Werror'
        
      - name: Functional tests
        run: |
          ./bin/dominatedsets --help
          ./bin/dominatedsets --help
          ./bin/eaf --help
          ./bin/epsilon --help
          ./bin/hv --help
          ./bin/igd --help
          ./bin/ndsort --help
          ./bin/nondominated --help
