name: C

on:
  push:
    branches-ignore: [gh-pages]
    paths:
      - '.github/workflows/C.yml'
      - 'c/Make*'
      - 'c/*.mk'
      - 'c/*.[ch]p?p?'

  pull_request:
    branches-ignore: [gh-pages]
    paths:
      - '.github/workflows/C.yml'
      - 'c/Make*'
      - 'c/*.mk'
      - 'c/*.[ch]p?p?'
  # Manual run
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    name: Build C code on ${{ matrix.os }} with ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
        cc: [ gcc ]
        include:
          - os: macOS-latest
            cc: clang
    env:
      CC: ${{ matrix.cc }}

    steps:
      - uses: actions/checkout@v4

      - name: Put MSYS2_MinGW64 on PATH
        if: runner.os == 'Windows'
        run: |
          echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{ runner.temp }}/msys64/mingw64/usr/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: $CC -v
        shell: bash

      - run: make -C c all DEBUG=1 WARN_FLAGS='-Werror'
        if: runner.os != 'Windows'
        # FIXME: How to install sanitizers in Windows?

      - run: make -C c all DEBUG=0 WARN_FLAGS='-Werror'

      - name: Functional tests
        run: |
          ./bin/dominatedsets --help
          ./bin/dominatedsets --help
          ./bin/eaf --help
          ./bin/epsilon --help
          ./bin/hv --help
          ./bin/igd --help
          ./bin/ndsort --help
          ./bin/nondominated --help

  msys2:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sys: [ clang64 ]
        cc: [ clang ]
        #- { sys: mingw64, cc: gcc }
        #- { sys: ucrt64,  cc: gcc }

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Disable autocrlf
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: >-
            make
          pacboy: >-
            ${{ matrix.cc }}:p

      - run: make -C c all DEBUG=1 WARN_FLAGS='-Werror' CC=${{ matrix.cc }}
      - run: make -C c all DEBUG=0 WARN_FLAGS='-Werror' CC=${{ matrix.cc }}

      - name: Functional tests
        run: |
          ./bin/dominatedsets --help
          ./bin/dominatedsets --help
          ./bin/eaf --help
          ./bin/epsilon --help
          ./bin/hv --help
          ./bin/igd --help
          ./bin/ndsort --help
          ./bin/nondominated --help
